groups:
  - name: alert.rules
    rules:
      - alert: PodsMissing
        expr: app:up:ratio{app!=""} < 0.9
        for: 10m
        labels:
          severity: page
        annotations:
          description: 'Pods missing from {{`{{`}} $labels.app {{`}}`}}: {{`{{`}} $value
            {{`}}`}}'
          help: Alerts when pods are missing.
          summary: Pods missing from {{`{{`}} $labels.app {{`}}`}}
      - alert: NoPodsRunning
        expr: app:up:ratio{app!=""} < 0.1
        for: 2m
        labels:
          severity: page
        annotations:
          description: 'No pods are running for {{`{{`}} $labels.app {{`}}`}}: {{`{{`}}
            $value {{`}}`}}'
          help: Alerts when no pods are running for a service.
          summary: No pods are running for {{`{{`}} $labels.app {{`}}`}}
      - alert: ProdPageLoadLatency
        expr:
          histogram_quantile(0.9, sum by(le) (rate(src_http_request_duration_seconds_bucket{job="sourcegraph-frontend",route!="raw"}[10m])))
          > 20
        labels:
          severity: page
        annotations:
          description: 'Page load latency > 20s (90th percentile over all routes; current
            value: {{`{{`}}$value{{`}}`}}s)'
          help: Alerts when the page load latency is too high.
          summary: High page load latency
      - alert: GoroutineLeak
        expr: go_goroutines >= 10000
        for: 10m
        annotations:
          description: '{{`{{`}} $labels.app {{`}}`}} has more than 10k goroutines. This
            is probably a regression causing a goroutine leak'
          help: Alerts when a service has excessive running goroutines.
          summary: Excessive number of goroutines
      - alert: FSINodesRemainingLow
        expr: sum by(instance) (container_fs_inodes_total{pod_name!=""}) > 3e+06
        labels:
          severity: page
        annotations:
          description: '{{`{{`}}$labels.instance{{`}}`}} is using {{`{{`}}humanize $value{{`}}`}}
            inodes'
          help: Alerts when a node's remaining FS inodes are low.
          summary: '{{`{{`}}$labels.instance{{`}}`}} remaining fs inodes is low'
      - alert: DiskSpaceLow
        expr: node:k8snode_filesystem_avail_bytes:ratio < 0.1
        annotations:
          help: Alerts when a node has less than 10% available disk space.
          summary: '{{`{{`}}$labels.exported_name{{`}}`}} has less than 10% available
            disk space'
      - alert: DiskSpaceLowCritical
        expr: node:k8snode_filesystem_avail_bytes:ratio{exported_name=~".*prod.*"} < 0.05
        labels:
          severity: page
        annotations:
          help: Alerts when a node has less than 5% available disk space.
          summary: Critical! {{`{{`}}$labels.exported_name{{`}}`}} has less than 5% available
            disk space
      - alert: GitserverDiskSpaceLow
        expr: src_gitserver_disk_space_available / src_gitserver_disk_space_total < 0.1
        annotations:
          help: Alerts when gitserverdisk space is low.
          summary: gitserver {{`{{`}}$labels.instance{{`}}`}} disk space is less than 10% of available disk space
      - alert: GitserverDiskSpaceLowCritical
        expr: src_gitserver_disk_space_available / src_gitserver_disk_space_total < 0.05
        labels:
          severity: page
        annotations:
          help: Alerts when gitserverdisk space is critically low.
          summary: Critical! gitserver {{`{{`}}$labels.instance{{`}}`}} disk space is less than 5% of available disk space
      - alert: SearcherErrorRatioTooHigh
        expr: searcher_errors:ratio10m > 0.1
        for: 20m
        annotations:
          help: Alerts when the search service has more than 10% of requests failing.
          summary: Error ratio exceeds 10%
      - alert: PrometheusMetricsBloat
        expr:
          http_response_size_bytes{handler="prometheus",job!="kubernetes-apiservers",job!="kubernetes-nodes",quantile="0.5"}
          > 20000
        annotations:
          help: Alerts when a service is probably leaking metrics (unbounded attribute).
          summary: '{{`{{`}}$labels.job{{`}}`}} in {{`{{`}}$labels.ns{{`}}`}} is probably
            leaking metrics (unbounded attribute)'
